output-format: text

strictness: medium

dodgy:
  run: true

mccabe:
  run: true

mypy:
  run: false
  ignore_missing_imports: true

pep257:
  run: false

pep8:
  run: true

profile_validator:
  run: true

pyflakes:
  run: true

pylint:
  run: true

pyroma:
  run: true

vulture:
  run: false
